#log_settings
output_dir : model
log : True

# Directory path settings
features_path : ../../../data/feature
feature_groups_path : ../../../data/feature_groups
label_pth : ../../../data/raw/train_labels.csv

# Optuna settings
use_optuna : False
OPTUNA_boosting_type : gbdt # gbdt(default), rf, dart, goss
OPTUNA_num_trial : 100
OPTUNA_num_boost_round : 1600
OPTUNA_early_stopping_rounds : 100
OPTUNA_only_first_fold : True 

# Model training settings
eval_interval : 10 # model_trainのevalを何エポック毎に出力するか
only_first_fold : False
show_importance : True
create_oofs : True

# params
training_params : {
  objective: binary, 
  metric: custom, 
  n_estimators : 1000,
  early_stopping_round : 1000,
  seed : 42,
  boosting : gbdt, # gbdt(default), rf, dart, goss
  learning_rate : 0.005, 
  min_child_samples : 2400,
  num_leaves : 100,
  max_bins : 511,
  force_col_wise : True
} 
# from https://www.kaggle.com/code/ambrosm/amex-lightgbm-quickstart

# Feature selection settings
# value に allと設定した場合、全ての特徴量が使用される
using_features : {
  Basic_Stat : all,
  Period_Basic_Stat : all,
  Date              : all,
  Last_mean_diff : all,
  Lag_diff : all
}
