#log_settings
output_dir : model
log : True

# Directory path settings
features_path : ../../../data/feature
feature_groups_path : ../../../data/feature_groups
label_pth : ../../../data/raw/train_labels.csv

# Optuna settings
use_optuna : False
OPTUNA_boosting_type : gbdt # gbdt(default), rf, dart, goss
OPTUNA_num_trial : 100
OPTUNA_num_boost_round : 1000
OPTUNA_early_stopping_rounds : 100
OPTUNA_only_first_fold : True 

# Model training settings
eval_interval : 100 # model_trainのevalを何エポック毎に出力するか
only_first_fold : False
show_importance : True
create_oofs : True

# params
training_params : {
        objective: 'binary',
        metric: "binary_logloss",
        boosting: 'dart',
        seed: 42,
        num_leaves: 100,
        learning_rate: 0.01,
        feature_fraction: 0.20,
        bagging_freq: 10,
        bagging_fraction: 0.50,
        n_jobs: -1,
        lambda_l2: 2,
        min_data_in_leaf': 40,
        n_estimators : 10000
        }
# from https://www.kaggle.com/code/ambrosm/amex-lightgbm-quickstart

# Feature selection settings
# value に allと設定した場合、全ての特徴量が使用される
using_features : {
  all_features : importance_top100,
}