logdir : out
log : True
features_path : ../../../data/feature
label_pth : ../../../data/raw/train_labels.csv
#'../../../data/raw/train_data.ftr'
ONLY_FIRST_FOLD : True

# Optuna settings

optuna_trial : 150
num_boost_round : 1600

using_features : {
  Basic_Stat : [B_1_last, B_2_last, B_3_last, B_1_max, B_2_max, B_3_max],
  Period_Basic_Stat : [B_1_max_100days, B_2_max_100days, B_3_max_100days, B_4_max_100days]
}