#log_settings
output_dir : model
log : True

features_path : ../../../data/feature
feature_groups_path : ../../../data/feature_groups
label_pth : ../../../data/raw/train_labels.csv

# Optuna settings
use_optuna : False
OPTUNA_num_trial : 100
OPTUNA_num_boost_round : 300
OPTUNA_early_stopping_rounds : 50
OPTUNA_only_first_fold : True 

# Model training settings
eval_interval : 10 # model_trainのevalを何エポック毎に出力するか
num_boost_round : 1800
early_stopping_rounds : 300
only_first_fold : False

# Feature selection
# value に allと設定した場合、全ての特徴量が使用される
using_features : {
  Basic_Stat : importance_top100,
  #Period_Basic_Stat : [B_1_max_100days, B_2_max_100days, B_3_max_100days, B_4_max_100days]
}