#log_settings
output_dir : model
log : True

# Directory path settings
features_path : ../../../data/feature
feature_groups_path : ../../../data/feature_groups
label_pth : ../../../data/raw/train_labels.csv

# Optuna settings
use_optuna : True
OPTUNA_num_trial : 2
OPTUNA_num_boost_round : 500
OPTUNA_early_stopping_rounds : 50
OPTUNA_only_first_fold : True
OPTUNA_GPU : True

# Model training settings
eval_interval : 10 # model_trainのevalを何エポック毎に出力するか
only_first_fold : False
show_importance : True
create_oofs : True
focal_loss : False

# params
training_params : {
    n_estimators : 200,
    early_stopping_rounds : 10,
    eval_metric: logloss,
    objective : binary:logistic,
    booster : gbtree, # gblinear or dart
    learning_rate : 0.2,
    tree_method : gpu_hist, 
    predictor : gpu_predictor,
    enable_categorical : True,
    random_state : 42, 
    # optuna params
    max_depth : 4, 
    subsample : 0.8,
    colsample_bytree : 0.6, 
}

# Feature selection settings
# value に allと設定した場合、全ての特徴量が使用される
using_features : {
  Basic_Stat : importance_top100,
}

categorical : ['B_30_last', 'B_38_last', 'D_114_last', 'D_116_last', 'D_117_last', 
               'D_120_last', 'D_126_last', 'D_63_last', 'D_64_last', 'D_66_last', 'D_68_last']