#log_settings
output_dir : model
log : True

features_path : ../../../data/feature
label_pth : ../../../data/raw/train_labels.csv

# Optuna settings
use_optuna : False
optuna_num_trial : 100
OPTUNA_ONLY_FIRST_FOLD : True 

# Model training settings
eval_interval : 10 # model_trainのevalを何エポック毎に出力するか
num_boost_round : 300
ONLY_FIRST_FOLD : False
show_importance : True

# Feature selection
# value に allと設定した場合、全ての特徴量が使用される
using_features : {
  Basic_Stat : all,
  Period_Basic_Stat : []
}